server: 
  port: 9001
spring: 
  application:  
    name: didablue
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.117.125:3306/didablue_background?useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://47.107.229.97:3306/didablue_background?useUnicode=true&characterEncoding=UTF-8
    #url: jdbc:mysql://127.0.0.1:3306/didablue_background?useUnicode=true&characterEncoding=UTF-8
    username: root
    #password: 123456
    password: didapassword2017
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: false 
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
logging:
  level:
    com.simons.cn.springbootdemo.dao.system:
      debug

